#!/usr/bin/env python3
"""Build the single-file bundle agentic-semgrep-rules.yaml from rules/**/*.yaml.

Semgrep prefixes rule ids with the config path when it loads a directory, so the Python and
JavaScript rules that share an id (for example llm-output-to-sql) stay distinct. Concatenated
into one file they would collide, and Semgrep silently keeps only one of them (verified on
1.179.0: 30 of 36 rules survived). The bundle therefore prefixes every id with its language
and category, for example python.injection.llm-output-to-sql.

Usage:
  python3 scripts/bundle.py                 # writes agentic-semgrep-rules.yaml at the repo root
  python3 scripts/bundle.py --out FILE      # writes elsewhere (the release workflow uses dist/)
  python3 scripts/bundle.py --check         # exit 1 if the committed bundle is stale
"""
from __future__ import annotations

import io
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
RULES = ROOT / "rules"
DEFAULT_OUT = ROOT / "agentic-semgrep-rules.yaml"


def build() -> str:
    rules = []
    for path in sorted(RULES.rglob("*.yaml")):
        rel = path.relative_to(RULES)
        language, category = rel.parts[0], rel.parts[1]
        for rule in yaml.safe_load(path.read_text())["rules"]:
            rule = dict(rule)
            rule["id"] = f"{language}.{category}.{rule['id']}"
            rules.append(rule)
    buf = io.StringIO()
    buf.write(
        "# agentic-semgrep-rules: single-file bundle, generated by scripts/bundle.py from rules/.\n"
        "# Do not edit by hand; edit the rule under rules/<language>/<category>/ and rerun the script.\n"
        f"# {len(rules)} rules. Ids are prefixed with language and category so none collide.\n"
        "# https://github.com/basitalisandhu/agentic-semgrep-rules (MIT)\n"
    )
    yaml.safe_dump({"rules": rules}, buf, sort_keys=False, width=100, allow_unicode=True)
    return buf.getvalue()


def main(argv: list[str]) -> int:
    out = DEFAULT_OUT
    if "--out" in argv:
        out = pathlib.Path(argv[argv.index("--out") + 1])
    text = build()
    if "--check" in argv:
        current = out.read_text() if out.exists() else ""
        if current != text:
            print(f"{out} is stale; run python3 scripts/bundle.py")
            return 1
        print(f"{out} is up to date")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
